# Generated by Django 4.2.13 on 2025-09-09 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLibrary',
            fields=[
                ('lib_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('documents', models.TextField(blank=True, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=255, null=True)),
                ('img_path', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='세션 제목')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsightTrends',
            fields=[
                ('car_model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('model_3d_path', models.CharField(blank=True, max_length=255, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True, verbose_name='평균 평점')),
                ('review_categories', models.JSONField(blank=True, null=True, verbose_name='리뷰 카테고리 통계')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, verbose_name='사용자 이름')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='회사명')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='부서명')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='직책')),
                ('profile_image', models.TextField(blank=True, null=True, verbose_name='프로필 이미지 URL')),
                ('background_image', models.TextField(blank=True, null=True, verbose_name='배경 이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='계정 생성일자')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_id', models.CharField(blank=True, max_length=50, null=True)),
                ('car_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review', models.TextField()),
                ('tags', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='JJACKLETTE.insighttrends')),
            ],
        ),
        migrations.CreateModel(
            name='RecentArticle',
            fields=[
                ('article_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('explain', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_articles', to='JJACKLETTE.insighttrends')),
            ],
        ),
        migrations.CreateModel(
            name='PromptLog',
            fields=[
                ('prompt_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_prompt', models.TextField()),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('result_type', models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('3d', '3D'), ('4d', '4D')], max_length=50, null=True)),
                ('result_path', models.CharField(blank=True, max_length=255, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_logs', to='JJACKLETTE.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryComments',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comments', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='JJACKLETTE.assetlibrary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EngineeringSpec',
            fields=[
                ('spec_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('length', models.CharField(blank=True, max_length=20, null=True, verbose_name='전장')),
                ('width', models.CharField(blank=True, max_length=20, null=True, verbose_name='전폭')),
                ('height', models.CharField(blank=True, max_length=20, null=True, verbose_name='전고')),
                ('wheelbase', models.CharField(blank=True, max_length=20, null=True, verbose_name='축거')),
                ('seating_capacity', models.CharField(blank=True, max_length=10, null=True, verbose_name='승차정원')),
                ('weight', models.CharField(blank=True, max_length=20, null=True, verbose_name='공차중량')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineering_specs', to='JJACKLETTE.insighttrends')),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetlibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_libraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('like_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='JJACKLETTE.librarycomments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AssetLikes',
            fields=[
                ('like_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_likes', to='JJACKLETTE.assetlibrary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_asset_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('asset_library', 'user')},
            },
        ),
    ]
