# Generated by Django 4.2.13 on 2025-08-07 06:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLibrary',
            fields=[
                ('lib_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documents', models.TextField(blank=True, null=True)),
                ('img_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsightTrends',
            fields=[
                ('car_model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('e_mail', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentiment_score', models.FloatField()),
                ('mentioned_features', models.TextField(blank=True, null=True)),
                ('car_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JJACKLETTE.insighttrends')),
            ],
        ),
        migrations.CreateModel(
            name='PromptLog',
            fields=[
                ('prompt_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_prompt', models.TextField()),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JJACKLETTE.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryComments',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comments', models.TextField()),
                ('lib_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JJACKLETTE.assetlibrary')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JJACKLETTE.users')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedResult',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(max_length=50)),
                ('result_path', models.CharField(max_length=255)),
                ('result', models.TextField(blank=True, null=True)),
                ('prompt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JJACKLETTE.promptlog')),
            ],
        ),
        migrations.CreateModel(
            name='EngineeringSpec',
            fields=[
                ('spec_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cd_value', models.FloatField()),
                ('weight', models.IntegerField()),
                ('material_al_ratio', models.FloatField()),
                ('wheel_base', models.IntegerField()),
                ('pedestrian_safety_score', models.FloatField()),
                ('sensor_ready', models.BooleanField()),
                ('car_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JJACKLETTE.insighttrends')),
            ],
        ),
        migrations.CreateModel(
            name='DesignMaterial',
            fields=[
                ('material_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_type', models.CharField(max_length=100)),
                ('usage_area', models.CharField(max_length=100)),
                ('car_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JJACKLETTE.insighttrends')),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JJACKLETTE.users'),
        ),
        migrations.AddField(
            model_name='assetlibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JJACKLETTE.users'),
        ),
        migrations.CreateModel(
            name='SalesStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('units_sold', models.IntegerField()),
                ('car_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JJACKLETTE.insighttrends')),
            ],
            options={
                'unique_together': {('car_model_id', 'year', 'month')},
            },
        ),
    ]
