# Generated by Django 4.2.13 on 2025-09-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JJACKLETTE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
