# Generated by Django 4.2.13 on 2025-09-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JJACKLETTE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlibrary',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='assets_cover_image/'),
        ),
        migrations.AlterField(
            model_name='assetlibrary',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='assets/'),
        ),
    ]
