# Generated by Django 4.2.13 on 2025-09-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JJACKLETTE', '0002_userreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='insighttrends',
            name='average_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='평균 평점'),
        ),
        migrations.AddField(
            model_name='insighttrends',
            name='review_categories',
            field=models.JSONField(blank=True, null=True, verbose_name='리뷰 카테고리 통계'),
        ),
    ]
