# Generated by Django 4.2.13 on 2025-09-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JJACKLETTE', '0002_assetlibrary_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlibrary',
            name='lib_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
