# Generated by Django 4.2.13 on 2025-09-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JJACKLETTE', '0003_assetlibrary_lib_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetlibrary',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='assetlibrary',
            name='documents',
        ),
    ]
